### ISSUE TITLE
get_course_owners()

### ISSUE THREAD

**Issue by mudrd8mz** [cperves/moodle-admin-legacyfilesmigration#6]
This function does not have the component prefix and is defined in the global scope. 

I am wondering if it would be better to use the core function `get_enrolled_users()` in combination with some appropriate capability (`moodle/course:managefiles` that might be relevant here?)

**Comment by cperves** [comment]
The demand of users was to attribute files to editing teachers who are supposed to have created the course so to be owner of files
In our platform legacyfiles respository is no more active but while restoring courses legacyfiles are restored as legacyfiles
I checked the role and moodle/course:managefile would be ok.
So I'll change this since it is more moodle minded.

**Comment by cperves** [comment]
made
